use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AssetFamilies {
    /// The asset family's stable identifier — a class of media with one shared
    /// shape. Unique per tenant.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// What the asset family is called, per language tag.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// How a file of this family is named, so an import can bind a file to a
    /// product without a mapping table. `source` is the product value the file
    /// name is built from, `pattern` how it is assembled, `allowed_extensions`
    /// what may be uploaded.
    #[serde(rename = "naming_convention", default)]
    pub naming_convention: serde_json::Value,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
