use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AssociationTypes {
    /// The kind of relation between two products. Unique per tenant.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Declares that a relation of this kind carries a quantity — a bundle, a
    /// bill of materials. `product_associations.quantity` is where that number
    /// goes, and it is meaningless without this flag.
    #[serde(rename = "is_quantified", default)]
    pub is_quantified: bool,
    /// Declares the relation symmetric — an accessory of A is an accessory of B.
    /// It is a declaration a client reads: this app stores one row per direction
    /// and does not create the mirror for you.
    #[serde(rename = "is_two_way", default)]
    pub is_two_way: bool,
    /// What the relation is called in a product form, per language tag.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
}
