use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AttributeGroups {
    /// The group's stable identifier, and the value an `AttributeField` carries as
    /// its `group` — a SECTION of the product form, not a label. Unique per
    /// tenant and the key an import joins on.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// The section heading a person sees, keyed by language tag. The code is never
    /// shown to an operator; a tag nobody translated falls back to the next filled
    /// one, then to English.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// Where this section sits in a form, ascending. Sections that tie keep the
    /// order the database returns them in.
    #[serde(rename = "position", default)]
    pub position: i64,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
