use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Families {
    /// The family's stable identifier — which set of attributes a product of
    /// this family HAS. Unique per tenant, and the value `GET
    /// /products/attribute-schema?family_code=` resolves.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Which attribute code carries the product's main image — the one a grid
    /// thumbnail and a picker read.
    #[serde(rename = "image_attribute", default)]
    pub image_attribute: String,
    /// Which attribute CODE carries the display name of a product in this family.
    /// A product's name is an attribute, not a column, and which attribute it is,
    /// is per family. Null falls back to the `default_label_attribute` setting and
    /// then to the conventional `name`.
    #[serde(rename = "label_attribute", default)]
    pub label_attribute: String,
    /// What the family is called, per language tag — the name an operator picks
    /// from, while the code is what everything else joins on.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
