use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FamilyVariants {
    /// The attribute codes a product model splits its variants on. Two shapes are
    /// in the wild and both are read: a bare list of codes, or one entry per
    /// level, outermost first — `[{"level": 1, "axes": ["colour"]}, {"level": 2,
    /// "axes": ["size"]}]`. An attribute named here is READ-ONLY on the model and
    /// set on each variant, which is what `AttributeField.readonly_reason`
    /// reports.
    #[serde(rename = "axes", default)]
    pub axes: serde_json::Value,
    /// The variant structure's stable identifier — how this family splits, not
    /// which product it splits. Unique per tenant.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The family this variant structure belongs to. A family may carry several,
    /// and a product names the one it follows through `family_variant_id`.
    #[serde(rename = "family_id", default)]
    pub family_id: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// What the variant structure is called, per language tag.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
