use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Form {
    /// When the form was first stored.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The form itself: a FormKit schema, held as a flat ARRAY of nodes (it
    /// defaults to `[]`, never to an object) and rendered verbatim by the
    /// storefront.
    /// 
    /// Read it as the field list. Every node carrying a non-empty `name` collects
    /// one value and writes it into a submission's `data` under exactly that name
    /// — the example below produces `{"company": …, "email": …, "message":
    /// …}` — while `$el` content nodes and `$rxStep` step markers collect
    /// nothing. Order is render order, and a `$rxStep` marker starts a new wizard
    /// step.
    /// 
    /// See the `FormKitNode` schema for what a node may carry.
    #[serde(rename = "definition", default)]
    pub definition: Vec<crate::models::FormKitNode>,
    /// The form's own id, generated by the database. It is what a submission's
    /// `form_id` points at and what the Cockpit and the storefront BFF hold once
    /// they have resolved a form, so it outlives a rename of the slug.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Free-form metadata on the FORM, which this app neither reads nor writes:
    /// yours to key however an integration needs, stored and returned verbatim.
    /// (The metadata this app does write is on a SUBMISSION — see
    /// `FormSubmissionMetadata`.)
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    /// What this form is called in the Cockpit's form list. Operator-facing only
    /// — the storefront never renders it, so renaming a form breaks no page.
    #[serde(rename = "name", default)]
    pub name: String,
    /// Everything about a form that is not a field: what the storefront renders
    /// around the inputs, what happens after a successful submit, and who is told
    /// about it. Open jsonb, so an unknown key is stored and handed back rather
    /// than refused — the keys below are the ones something actually READS, and
    /// each says which reader that is. Null on a form nobody has configured, which
    /// is not an error: every one of these has a fallback.
    #[serde(rename = "settings", default)]
    pub settings: crate::models::FormSettings,
    /// URL-safe identifier, unique per tenant. This is the name a storefront
    /// resolves a form by (`GET /v1/forms?slug=contact&status=live&limit=1`), so
    /// it is part of the page's contract: changing it changes which form a page
    /// renders. Lower-case letters, digits and inner hyphens.
    #[serde(rename = "slug", default)]
    pub slug: String,
    /// Lifecycle. `draft` while it is being built; `live` once the storefront may
    /// render it — the cover BFF resolves live forms only, so a draft is a 404
    /// on the storefront and never a broken page; `archived` for a form that is
    /// kept for its submissions but no longer offered. Default 'draft'.
    #[serde(rename = "status", default)]
    pub status: String,
    /// The tenant this row belongs to — the store slug, not an id. Set by the
    /// platform from the authenticated context, never by a caller; a write that
    /// carries it is ignored, and no request can read another tenant's rows by
    /// sending a different one.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// When the form was last written. This app stamps it on every PUT, so it is
    /// the timestamp an editor sorts by.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
