use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MeasurementFamilies {
    /// The measurement family's stable identifier. A `measure` attribute names one
    /// and then offers that family's units.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// What the measurement family is called, per language tag.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// The unit every value of this family is converted to before it is compared
    /// or sorted — the unit each `convert_factor` is relative to.
    #[serde(rename = "standard_unit", default)]
    pub standard_unit: String,
    /// The units this family offers. `convert_factor` multiplies a value into
    /// `standard_unit`, so a gram is 0.001 kilograms; `symbol` is what a form
    /// prints next to the number.
    #[serde(rename = "units", default)]
    pub units: serde_json::Value,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
