use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderListSummary {
    /// When the list was created.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The list, by id. Generated by the database and the only way to address it
    /// — every /orderlists/{id} route takes this uuid.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Positions this list holds. Counted server-side so a badge costs no extra
    /// call — the collection deliberately does NOT carry the positions
    /// themselves.
    #[serde(rename = "item_count", default)]
    pub item_count: i64,
    /// What the list is FOR — the `code` of one of the tenant's own kinds (GET
    /// /orderlists/kinds). Nothing in this app branches on it: it groups and
    /// filters lists, it does not change how positions are stored or how a
    /// conversion runs. A merchant may add their own (reagent lists, sample lists)
    /// without a release of this app.
    #[serde(rename = "kind", default)]
    pub kind: String,
    /// Free-form data the tenant keeps on the list — an ERP requisition number,
    /// a department, whatever an integration needs to recognise the list again.
    /// Never read by this app, and never merged: a write replaces the whole
    /// document.
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    /// What the buyer calls this list. Free text, at least one character, and not
    /// unique: two contacts may both keep a "Weekly office supplies". It is also
    /// the name a NEW cart gets when POST /orderlists/{id}/cart creates one.
    #[serde(rename = "name", default)]
    pub name: String,
    /// The organization the sharing is scoped to. Null means the list can only
    /// ever be the owner's own: `shared` is meaningless without it, because there
    /// is no set of people to share with. It is also what the order conversion
    /// hands the orders app as the buying organization.
    #[serde(rename = "organization_id", default)]
    pub organization_id: String,
    /// The contact who owns the list. Ownership IS the authorization here: a
    /// caller the gateway resolved to a contact sees their own lists plus their
    /// organization's shared ones, and may write only their own — unless
    /// `shared_lists_editable` opens a shared list to the whole owning
    /// organization. Set once at create; no route moves a list to another owner.
    #[serde(rename = "owner_id", default)]
    pub owner_id: String,
    /// The owner's display name as it stood when the list was created — a
    /// snapshot, so renaming the contact does not rewrite it. Carried so a shared
    /// list can say whose it is without a call to the contacts app.
    #[serde(rename = "owner_name", default)]
    pub owner_name: String,
    /// Dead column: what `shared` was called before the 2026-06-20 rename
    /// (`public` is a reserved word in most SDK target languages). Nothing reads
    /// or writes it, so it is `false` on every list written since; it is still
    /// returned only because the additive provisioner never dropped the column.
    /// Read `shared` — this field says nothing about who may see the list.
    #[serde(rename = "public", default)]
    pub public: bool,
    /// Whether the OWNING ORGANIZATION may see this list. False — the default
    /// — keeps it private to `owner_id`, and a foreign private list answers 404
    /// rather than 403, so an outsider learns nothing from the difference. True
    /// lets every contact of `organization_id` READ it, and write it only where
    /// the tenant turned on the `shared_lists_editable` setting. A list with no
    /// `organization_id` shares with nobody however this is set.
    #[serde(rename = "shared", default)]
    pub shared: bool,
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a
    /// caller — it is the row-level security scope, not a field, and every row a
    /// request can reach is inside it already.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// When the list or ANY of its positions last changed — adding, updating or
    /// removing a position touches the list — so this is the timestamp a
    /// "recently used" sort should read. It is also the default sort of GET
    /// /orderlists (`updated_at.desc`).
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
