use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderListKindRow {
    /// What `lists.kind` stores. Lowercase, immutable once created — renaming it
    /// would orphan every list that carries it, so a merchant who wants a
    /// different code creates a new kind and moves the lists over.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the kind was created — the install for a seeded one.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// What this kind is FOR, in the tenant's own words — the sentence a select
    /// shows underneath the title. `descriptions` carries the localized forms.
    /// Same caveat as `title`: a kind seeded before 0.15.0 may hold a serialized
    /// locale map here (PE-450).
    #[serde(rename = "description", default)]
    pub description: String,
    /// Localized descriptions, keyed by language tag. Same fallback as `labels`:
    /// `description` is what a reader gets when their tag is missing.
    #[serde(rename = "descriptions", default)]
    pub descriptions: serde_json::Value,
    /// The kind, by id. Generated by the database and what every
    /// /orderlists/kinds/{id} route addresses — the `code` is the identity a
    /// LIST carries, the id is the identity a route takes.
    #[serde(rename = "id", default)]
    pub id: String,
    /// The kind a list created without one gets. Exactly one row carries it —
    /// promoting a kind demotes the previous holder — and the market-scoped
    /// `default_kind` setting still wins where a tenant set it.
    #[serde(rename = "is_default", default)]
    pub is_default: bool,
    /// Seeded on install rather than created by the merchant. It changes nothing
    /// about what may be done to the row: a system kind is still renameable, still
    /// retirable, and still deletable once no list carries it.
    #[serde(rename = "is_system", default)]
    pub is_system: bool,
    /// Localized titles, keyed by language tag. `title` is what a reader gets when
    /// their tag is missing, so this only ever adds languages — it never
    /// replaces the plain one.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// Where this kind sits in a select, ascending. Ties fall back to the code, so
    /// the order is stable.
    #[serde(rename = "position", default)]
    pub position: i64,
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a
    /// caller — it is the row-level security scope, not a field, and every row a
    /// request can reach is inside it already.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// What a person reads, in the tenant's own words. `labels` carries the
    /// localized forms. Kinds seeded before 0.15.0 hold a serialized locale map
    /// here instead — the seed wrote its `{en, de}` map into this `text` column
    /// and left `labels` null, and Postgres stores such a map as its JSON text
    /// rather than refusing it (PE-450). Those rows are not repaired by the fix; a
    /// repair is a data change.
    #[serde(rename = "title", default)]
    pub title: String,
    /// Semantic badge colour. The client owns what each tone looks like; the kind
    /// only says what the value MEANS.
    #[serde(rename = "tone", default)]
    pub tone: String,
    /// When the kind was last written.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
