use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProductCategories {
    /// The category it is filed into. One row per (product, category), whichever
    /// way it got there.
    #[serde(rename = "category_id", default)]
    pub category_id: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Sort order of this product inside the category.
    #[serde(rename = "position", default)]
    pub position: i64,
    /// The product filed into the category. Deleting the product deletes the
    /// membership with it.
    #[serde(rename = "product_id", default)]
    pub product_id: String,
    /// How the membership came about: 'manual' is hand-picked, 'rule' was
    /// materialized by a category rule. The two never touch each other — a
    /// recompute only ever inserts and deletes `rule` rows, so a hand-picked
    /// membership survives every pass.
    #[serde(rename = "source", default)]
    pub source: String,
}
