use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ProductAssociations {
    /// Which kind of relation this is — the `association_types` row.
    #[serde(rename = "association_type_id", default)]
    pub association_type_id: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Order in which the targets are shown, ascending.
    #[serde(rename = "position", default)]
    pub position: i64,
    /// The product the relation starts at — the one whose detail page shows it.
    #[serde(rename = "product_id", default)]
    pub product_id: String,
    /// How many of the target belong to the source — the 4 in "this bundle
    /// contains 4 casters". Only meaningful when the association type carries
    /// `is_quantified`; null on an ordinary cross-sell.
    #[serde(rename = "quantity", default)]
    pub quantity: f64,
    /// The product the relation points at — the accessory, the spare part, the
    /// cross-sell.
    #[serde(rename = "target_product_id", default)]
    pub target_product_id: String,
}
