use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReferenceEntities {
    /// The entity's stable identifier — a domain of records the catalog POINTS
    /// AT instead of duplicating, so a brand is edited once and not on nine
    /// thousand products. Unique per tenant.
    #[serde(rename = "code", default)]
    pub code: String,
    /// When the row was created. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A client never sends one; it
    /// reads one back and uses it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// A delivery path or URL for the entity's own icon. Cosmetic — nothing in
    /// this app resolves it.
    #[serde(rename = "image", default)]
    pub image: String,
    /// What the entity is called, per language tag — the heading over its record
    /// list.
    #[serde(rename = "labels", default)]
    pub labels: serde_json::Value,
    /// When the row was last written. Server-set — it is not part of any request
    /// body.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
