use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Reservation {
    /// When the row was created. Server-set: it is in no request body, and a value
    /// sent for it is ignored.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// When this hold lapses. The sweeper — POST
    /// /inventories/reservations/sweep, and the 'expire-reservations' schedule
    /// that runs it every 15 minutes — releases everything past this moment
    /// exactly as a cancellation would, so an abandoned checkout stops holding
    /// stock on its own. Null means the row named no deadline: it is swept on its
    /// AGE instead once `reservation_ttl_minutes` is above 0, which is what makes
    /// turning that setting on retroactive.
    #[serde(rename = "expires_at", default)]
    pub expires_at: String,
    /// The row's own id, generated by the database. A caller never sends one —
    /// it reads one back and puts it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Which location is holding the goods for this order. Chosen at reserve time
    /// by the tenant's `allocation_strategy` — not by the caller, unless
    /// `ship_to.location_code` names one and the strategy is 'nearest'.
    #[serde(rename = "location_id", default)]
    pub location_id: String,
    /// Free-form, and one key this app writes itself: `backordered` — how much
    /// of this hold was not covered by stock on hand when it was taken. Absent on
    /// a hold that was fully covered.
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    /// The order this hold belongs to. The caller supplies it — this app mints
    /// nothing — and it is the handle POST /inventories/release and POST
    /// /inventories/commit act on, so it has to be the same string the order
    /// carries elsewhere. At least one character (CHECK `length(order_ref) > 0`).
    /// Not unique: an order holds one reservation per item, and they are released
    /// or committed together.
    #[serde(rename = "order_ref", default)]
    pub order_ref: String,
    /// The product being held, copied from the reserve call. Null when the item
    /// was identified by SKU.
    #[serde(rename = "product_id", default)]
    pub product_id: String,
    /// How much is being held, ALWAYS POSITIVE — the database CHECK is `quantity
    /// > 0`, because a hold of nothing is not a hold. It is added to
    /// `stock_levels.reserved` while the status is `active` and taken off again
    /// when the hold is released, expires or is committed. The matching ledger
    /// booking carries the same number NEGATIVE (see `stock_movements.quantity`).
    #[serde(rename = "quantity", default)]
    pub quantity: f64,
    /// The article number being held, copied from the reserve call. Null when the
    /// item was identified by product id.
    #[serde(rename = "sku", default)]
    pub sku: String,
    /// Where the hold stands in the reserve → commit | release lifecycle.
    /// 'active' — holding stock, and the ONLY status counted in
    /// `stock_levels.reserved`. 'committed' — the order shipped, so `on_hand`
    /// and `reserved` both fell. 'released' — the hold was given back, by POST
    /// /inventories/release or by the expiry sweeper. Both end states are final:
    /// nothing in this app moves a reservation back to active.
    #[serde(rename = "status", default)]
    pub status: String,
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a
    /// caller — it is the row-level security scope, not a field, and every row a
    /// request can reach is inside it already.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// When the hold last changed — in practice, when it moved out of `active`.
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
