use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StockLevel {
    /// When the row was created. Server-set: it is in no request body, and a value
    /// sent for it is ignored.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A caller never sends one —
    /// it reads one back and puts it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// The location this balance is held at — a `locations` row of this tenant
    /// (GET /inventories/locations). There is ONE stock row per (location, item):
    /// the same SKU in three warehouses is three rows, and what a storefront shows
    /// is their sum (POST /inventories/availability). Deleting the location
    /// deletes its stock rows with it.
    #[serde(rename = "location_id", default)]
    pub location_id: String,
    /// Free-form data the tenant keeps on this stock row, and ONE key this app
    /// reads: `backorder`. A literal boolean `true` there opts this item into
    /// backorders while `backorder_policy` is 'allow_per_sku' — anything else,
    /// including the string "true", does not, and the reservation is refused with
    /// 422. That is how a merchant backorders the supplier-stocked half of a
    /// catalogue without promising the rest.
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    /// How much is PHYSICALLY at this location, INCLUDING the units already
    /// promised to orders. It is a BALANCE, not a movement: the running total of
    /// every `stock_movements` booking for this (location, item), and no request
    /// writes it directly — POST /inventories/receive raises it, POST
    /// /inventories/commit lowers it when the order ships, the adjust routes
    /// correct it, and a create/update body naming it has it DROPPED (422 if it
    /// names nothing else). Never negative: the database CHECK is `on_hand >= 0`,
    /// so a correction that would go below zero is refused with 422 and no setting
    /// overrides it — `allow_negative_stock` is about available stock, not about
    /// this. available (`on_hand` − `reserved`) is DERIVED and never stored —
    /// POST /inventories/availability and GET /inventories/reorder-alerts compute
    /// it on read.
    #[serde(rename = "on_hand", default)]
    pub on_hand: f64,
    /// The product this row tracks, as the products app knows it. A row tracks a
    /// `product_id` or a `sku` — the database insists on at least one (CHECK
    /// `product_id is not null or sku is not null`) — and matching is exact: a
    /// row keyed by SKU is not found by product id.
    #[serde(rename = "product_id", default)]
    pub product_id: String,
    /// The available quantity at or below which this row belongs on the
    /// replenishment worklist (GET /inventories/reorder-alerts). Null falls back
    /// to the `reorder_point_default` setting, so replenishment works without a
    /// threshold per SKU; 0 never alerts, which is how one row opts out.
    #[serde(rename = "reorder_point", default)]
    pub reorder_point: f64,
    /// How much of `on_hand` is already promised — the sum of the ACTIVE
    /// reservations at this row. Reserving raises it; releasing, expiring or
    /// committing lowers it. Never negative (CHECK `reserved >= 0`). It does NOT
    /// reduce `on_hand`: the goods are still in the building until the shipment is
    /// committed, which is why the sellable figure is the difference of the two
    /// and not either one alone. available (`on_hand` − `reserved`) is DERIVED
    /// and never stored — POST /inventories/availability and GET
    /// /inventories/reorder-alerts compute it on read.
    #[serde(rename = "reserved", default)]
    pub reserved: f64,
    /// The article number this row tracks when there is no product id, which is
    /// the normal case for an ERP-stocked catalogue. Exact match, and the identity
    /// every stock call may use instead of a uuid.
    #[serde(rename = "sku", default)]
    pub sku: String,
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a
    /// caller — it is the row-level security scope, not a field, and every row a
    /// request can reach is inside it already.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// When this row was last written. Every balance change stamps it, so it
    /// doubles as "when did this item last move at this location".
    #[serde(rename = "updated_at", default)]
    pub updated_at: String,
}
