use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StockMovement {
    /// When the booking was written — the ledger's own clock and its natural
    /// order, which is why `?order=created_at.desc` is the feed order. There is no
    /// `updated_at`: the ledger is append-only, and a correction is another
    /// booking rather than an edit.
    #[serde(rename = "created_at", default)]
    pub created_at: String,
    /// The row's own id, generated by the database. A caller never sends one —
    /// it reads one back and puts it in the path of every later call.
    #[serde(rename = "id", default)]
    pub id: String,
    /// Where the booking happened. Copied from the call that caused it, not a
    /// foreign key — a movement outlives the location row it names.
    #[serde(rename = "location_id", default)]
    pub location_id: String,
    /// Free-form, and two keys this app writes itself: `backordered` — on a
    /// `reserve` booking, how much of the hold was not covered by stock on hand;
    /// `shortfall` — on a `shipment` booking, how much was committed that was
    /// not physically there (`on_hand` floors at 0, so the difference is recorded
    /// here instead of vanishing). Neither key is present on a booking that needed
    /// neither.
    #[serde(rename = "metadata", default)]
    pub metadata: serde_json::Value,
    /// The order this booking belongs to, for the bookings an order causes —
    /// 'reserve', 'release', 'shipment', and a 'restock' that names one. Null for
    /// a receipt or a stocktake. It is the join that reconstructs one order's
    /// whole stock history: GET /inventories/movements?order_ref=…
    #[serde(rename = "order_ref", default)]
    pub order_ref: String,
    /// The product this booking is for, copied from the call. Null when the item
    /// was identified by SKU.
    #[serde(rename = "product_id", default)]
    pub product_id: String,
    /// The SIGNED size of the booking — a DELTA, never a balance, and
    /// deliberately the one quantity in this app with no bound on it.
    /// `stock_levels.on_hand`/`reserved` and `reservations.quantity` each carry a
    /// CHECK; this column carries none, because the SIGN is the direction of the
    /// booking and a rule that forbade one of them would forbid half the ledger.
    /// Positive adds to what the location holds ('inbound', 'restock', a positive
    /// 'adjustment'); negative takes it away ('shipment', a negative
    /// 'adjustment'). 'reserve' books the NEGATIVE of the quantity held (−5 for
    /// a hold of 5) while the reservation row itself carries +5: the movement says
    /// which way stock moved, the reservation says how much is being held. Summing
    /// this column for one (location, item) reconstructs `on_hand` — which is
    /// what makes the ledger an audit trail and not a log.
    #[serde(rename = "quantity", default)]
    pub quantity: f64,
    /// Why the booking happened, in a person's words — a delivery note number,
    /// 'stocktake 2026-03', 'damaged in transit'. Whether one is owed is the
    /// `movement_reason_required` setting ('none' | 'adjustments' | 'all'), never
    /// this column, which stays nullable so the tenant that requires nothing is
    /// not forced. The expiry sweeper writes 'reservation expired' on the releases
    /// it makes.
    #[serde(rename = "reason", default)]
    pub reason: String,
    /// The article number this booking is for, copied from the call. Null when the
    /// item was identified by product id.
    #[serde(rename = "sku", default)]
    pub sku: String,
    /// The tenant this row belongs to, as a slug. Set by the platform, never by a
    /// caller — it is the row-level security scope, not a field, and every row a
    /// request can reach is inside it already.
    #[serde(rename = "tenant_id", default)]
    pub tenant_id: String,
    /// What the booking records. 'inbound' — a receipt (+on_hand). 'adjustment'
    /// — a manual correction, the only type whose sign can go either way.
    /// 'reserve' — a hold taken for an order (`reserved` up, `on_hand`
    /// untouched). 'release' — a hold given back, by cancellation or by the
    /// expiry sweeper. 'shipment' — a committed reservation leaving the building
    /// (`on_hand` and `reserved` both down). 'restock' — a return that rejoined
    /// sellable stock. GET /inventories/vocabularies/movement-types serves these
    /// with the words a person reads for them.
    #[serde(rename = "type", default)]
    pub xtype: String,
}
