//! Revenexx Rust SDK for server-side applications.
//!
//! This crate is auto-generated by the Revenexx SDK Generator.
#![allow(
    dead_code,
    unused_imports,
    unused_mut,
    unused_variables,
    clippy::too_many_arguments
)]

pub mod client;
pub mod error;
pub mod id;
pub mod input_file;
pub mod models;
pub mod operator;
pub mod permission;
pub mod query;
pub mod role;
pub mod services;

pub use client::Client;
pub use error::Error;
pub use input_file::InputFile;
